# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/173zhAu7OhXvgEMG7-AXKm9c-NYe7QnKi
"""

# Calculadora de nota
grade1 = float(input("Grade 1: ").replace(',', '.'))
grade2 = float(input("Grade 2: ").replace(',', '.'))
grade3 = float(input("Grade 3: ").replace(',', '.'))

total = (grade1 + grade2 + grade3)/3

print(f"Total: {total:.1f}")
print("Parabéns, você foi aprovado!" if total >= 6 else "Ah. que pena, você reprovou!")